### ISSUE TITLE
About the label and csv file

### ISSUE THREAD

**Issue by stonewalking** [ilucasgoncalves/VAVL#4]
Hi author, 
I am quite interest about the paper.
I downloaded the dataset, but in the csv file, it has a EMOact label with value, 

However the actualy dataset annotation doesn't has this label, it has "A V D N" Can find the matched value.

It the label in csv file use some early version of the dataset?

**Comment by ilucasgoncalves** [comment]
Is this related to MSP-IMPROV dataset or CREMA-D?

**Comment by stonewalking** [comment]
MSP-IMPROV

Lucas Goncalves ***@***.***>于2023年9月23日 周六20:54写道：

**Comment by stonewalking** [comment]
> Is this related to MSP-IMPROV dataset or CREMA-D?

Is about the MSP-IMPROV dataset

**Comment by ilucasgoncalves** [comment]
Oh i see, this is just some naming I used when I generated the .csv file to save the labels in a organized way for training the model. It is not from a earlier version of the dataset.

I used this naming structure because I was following the naming structure used in the MSP-Podcast dataset, essentially: 

EmoAct = Arousal = A | EmoVal = Valence = V | EmoDom = Dominance = D

You might be confused on the reason why the EmoAct does not match the A value provided in the files from the original MSP-IMPROV files. This is happening because there is an error on the dataset annotation that the values for the rating scale of arousal (1 to 5) were actually flipped when this dataset was annotated (5 to 1). So when I generated this .csv file i took care of that already by mapping the individual annotation ratings, as:

Arousal ratings mapping = {
    5:1,
    4:2,
    3:3,
    2:4,
    1:5
    }
    
Note: only arousal ratings had this issue, dominance and valence are all good!

**Comment by stonewalking** [comment]
> Oh i see, this is just some naming I used when I generated the .csv file to save the labels in a organized way for training the model. It is not from a earlier version of the dataset.
> 
> I used this naming structure because I was following the naming structure used in the MSP-Podcast dataset, essentially:
> 
> EmoAct = Arousal = A | EmoVal = Valence = V | EmoDom = Dominance = D
> 
> You might be confused on the reason why the EmoAct does not match the A value provided in the files from the original MSP-IMPROV files. This is happening because there is an error on the dataset annotation that the values for the rating scale of arousal (1 to 5) were actually flipped when this dataset was annotated (5 to 1). So when I generated this .csv file i took care of that already by mapping the individual annotation ratings, as:
> 
> Arousal ratings mapping = { 5:1, 4:2, 3:3, 2:4, 1:5 }
> 
> Note: only arousal ratings had this issue, dominance and valence are all good!

Thank you author,
So it is okay to use the csv file in the code for training, right? ,like I don't need to edit it again?

**Comment by ilucasgoncalves** [comment]
yes, it is ok. The labels there are consistent with the original most up to date labels of the dataset.
