### ISSUE TITLE
For audio extraction from video or using audio dataset.

### ISSUE THREAD

**Issue by stonewalking** [ilucasgoncalves/VAVL#7]
Hi author, 

I see some of the multi-modal audio-visual recognition work.
Like you, use audio that extracted from video, why don't use the audio part of the dataset in MSP-IMPRO?
I see others they also do the same. Is there any special reason? Or it is not aligned?

KRs,
stone

**Comment by ilucasgoncalves** [comment]
I think it is totally fine you use the audio part of the dataset instead of extracting the audio directly from the video then processing it.

Here are some reasons I do it this way:

1. Consistency, most datasets will not provide audio files separate from videos. So doing this way makes the approach more applicable across datasets. Also for simplicity, using the audio directly from the video is usually more straightforward than having to check if everything is good with the separately provided audios and they are in agreement with the video content.
2. Synchronization: Sometimes a separately provided audio files might not be in sync with the video. So to avoid this issue might be better to directly extract from video.
